export default {
  // ACTIONS
  GET_LIBRARIES: 'GET_LIBRARIES',
  INCREASE_PAGE_ACTION: 'INCREASE_PAGE_ACTION',
  // MUTATIONS
  SET_LIBRARIES: 'SET_LIBRARIES',
  SET_FETCHED_LIBRARIES: 'SET_FETCHED_LIBRARIES',
  SET_LOADING: 'SET_LOADING',
  INCREASE_PAGE: 'INCREASE_PAGE',
  ADD_LIBS: 'ADD_LIBS',
}
